# Generated by Django 4.0.1 on 2022-01-24 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encadreur',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='encadreur',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='promoteur',
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='stage',
        ),
        migrations.AlterField(
            model_name='stage',
            name='intitule',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encadreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.encadreur')),
                ('promoteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.promoteur')),
                ('stage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.stage')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.groupe'),
        ),
        migrations.AddField(
            model_name='ficheevaluation',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.groupe'),
        ),
    ]
