# Generated by Django 4.0.1 on 2022-01-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_encadreur_specialite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='fourni_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.entreprise'),
        ),
    ]
