# Generated by Django 4.0.1 on 2022-01-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_stage_fourni_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='nom',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
