# Generated by Django 4.0.1 on 2022-01-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_groupe_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='palier',
            name='code_stage',
            field=models.IntegerField(null=True),
        ),
    ]
