# Generated by Django 4.0.1 on 2022-01-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_groupe_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stage',
            name='annee_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.datestage'),
        ),
    ]
